### PR TITLE
fix stop condition for epochs

### PR DESCRIPTION
**Pull request by plhijk**
`epoch` starts at 1, so `<` leads to one fewer epoch than expected

### CODE REVIEW

**Comment by syncrostone** [comment]
Thank you for catching this and submitting this pull request, sorry for the slow response. This fix looks good. Could you please add a test that ensures correct stopping conditions in [this test file](https://github.com/murraylab/PsychRNN/blob/master/test/backend/test_rnn.py) to ensure this error isn't reintroduced in the future?

**Comment by plhijk** [comment]
I'm new to unit testing. What would be an appropriate way to test it? Eg. change the local variables `epoch` and `performance` to attributes so they can be tested against training params?

**Comment by syncrostone** [comment]
Ideally testing shouldn’t require changing the code just to enable testing. To
get started, I would make sure you can successfully run pytest on the
existing tests locally. Then you can run the test you are developing
locally on its own while you are writing it. This package uses the pytest
unit testing framework so the documentation there should help if you get
stuck, but also feel free to ask me if not.

In this particular case I would just set verbosity to True in train_params
which makes it so the iter number is printed (with the loss) every
loss_epoch. Then you can check that you get the expected iters printed out
(and not unexpected iters). You should probably be able to do this using
capfd (https://docs.pytest.org/en/6.2.x/capture.html)
like I use to capture error messages in some of the test functions in the
same test file.

**Comment by plhijk** [comment]
Thanks for the guidance. I've corrected the while statement again to `(epoch - 1) * batch_size < training_iters` so it also works when `batch_size` does not divide `training_iters`. I also implemented a test to ensure the correct iteration number is printed.

**Comment by syncrostone** [comment]
Awesome, this looks great, thanks for writing the test! I’ll go through
this carefully and hopefully merge it next week.

**Comment by syncrostone** [comment]
Sorry it took so long for me to get to this! Great work with the tests and I just merged it.

**Pull request merged**
